[build]
  command = "npm run build"
  publish = "build/client"

[dev]
  command = "npm run dev"
  framework = "vite"

[template]
  required-extensions = ["supabase"]

# Ensure assetlinks.json is served correctly
[[headers]]
  for = "/.well-known/assetlinks.json"
  [headers.values]
    Content-Type = "application/json"

# Prevent redirects from breaking assetlinks.json
[[redirects]]
  from = "/.well-known/*"
  to = "/.well-known/:splat"
  status = 200
  force = true
